### ISSUE TITLE
"nestedObject = null" condition does not work

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-mongo#179]
```json
  "errors": [
        {
            "objectType": "error",
            "context": "rest/FindCommand/user/find(user:0.0.1-SNAPSHOT)/find/translateQuery",
            "errorCode": "mongo-translation:invalid-comparison",
            "msg": "{\"field\":\"nestedObject\",\"op\":\"$eq\",\"rvalue\":null}"
        }
    ]
```

**Comment by bserdar** [comment]
Fixed in https://github.com/lightblue-platform/lightblue-mongo/pull/180

Depends on https://github.com/lightblue-platform/lightblue-core/pull/519

**Comment by paterczm** [comment]
@bserdar 

A condition like that works now:
```json
{"field":"personalInformation","op":"=","rvalue":null}
```

However, $null string still doesn't:

```json
{"field":"personalInformation","op":"=","rvalue":"$null"}
```
Results in:
```json
"errors": [
        {
            "objectType": "error",
            "context": "rest/FindCommand/user/find(user:0.0.1-SNAPSHOT)/find/translateQuery",
            "errorCode": "mongo-translation:invalid-comparison",
            "msg": "{\"field\":\"personalInformation\",\"op\":\"$eq\",\"rvalue\":\"$null\"}"
        }
    ]
```
Am I misunderstanding how $null should work?

**Comment by bserdar** [comment]
I think I remember this one wrong. I don't see $null in the query spec, so
I don't think it is supposed to work.
